using System.Text.Json.Serialization;

namespace FractalGPT.SharpGPTLib.API.LLMAPI;

/// <summary>
/// Represents one of the possible response options returned by the model.
/// </summary>
[Serializable]
public class Choice
{
    /// <summary>
    /// The index of the option (starting from zero).
    /// </summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>
    /// The message generated by the model.
    /// </summary>
    [JsonPropertyName("message")]
    public LLMMessage Message { get; set; }

    /// <summary>
    /// The reason the model stopped generating the response.
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public string FinishReason { get; set; }

    /// <summary>
    /// The native reason for stopping, specific to the provider.
    /// </summary>
    [JsonPropertyName("native_finish_reason")]
    public string NativeFinishReason { get; set; }

    /// <summary>
    /// Log probabilities (optional, may be null).
    /// </summary>
    [JsonPropertyName("logprobs")]
    public object Logprobs { get; set; }

    /// <summary>
    /// Refusal reason (optional, may be null).
    /// </summary>
    [JsonPropertyName("refusal")]
    public string Refusal { get; set; }

    /// <summary>
    /// Reasoning provided by the model (optional).
    /// </summary>
    [JsonPropertyName("reasoning")]
    public string Reasoning { get; set; }

    /// <summary>
    /// Detailed reasoning steps (optional).
    /// </summary>
    [JsonPropertyName("reasoning_details")]
    public List<ReasoningDetail> ReasoningDetails { get; set; }
}
