using System.Text.Json.Serialization;

namespace FractalGPT.SharpGPTLib.API.LLMAPI;

/// <summary>
/// Represents one of the possible response options returned by the model.
/// </summary>
public class Choice
{
    /// <summary>
    /// The index of the option (starting from zero), indicating the order in which the model generated this option.
    /// </summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>
    /// The message generated by the model as part of this option.
    /// </summary>
    [JsonPropertyName("message")]
    public LLMMessage Message { get; set; }

    /// <summary>
    /// The reason the model stopped creating the response (e.g., "length" or "stop").
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public string FinishReason { get; set; }
}
